### ISSUE TITLE
Course management

### ISSUE THREAD

**Issue by booski** [dsv-su/play#10]
The course administrator for a given course (according to a daisy lookup) should have the ability to manage videos on their course(s).

This management ability should not extend to modifying videos that they are not listed as presenters on, but it should be possible to hide videos and generally manage their permissions.

**Comment by orkit** [comment]
The course administrator for a given course can manage presentations, change permissions and can hide presentations. The course administrator(s) is defined from a daisy lookup. Users with administrator or individual (permission edit) privileges override the hidden presentations.
