### ISSUE TITLE
Better playlist exposure

### ISSUE THREAD

**Issue by booski** [dsv-su/play#103]
The playlist feature is currently hard to discover, which is a shame since everyone I've shown it to has been really happy about it.

We should implement some kind of active choice to play a playlist via a dedicated button. For example each course could have a "play all" button.

Once this is in place the automatic inclusion of a playlist when opening a presentation can probably be dropped.

**Comment by pavelsokolov** [comment]
'Play all' button is added now.

![Screenshot 2022-07-14 at 16 55 47](https://user-images.githubusercontent.com/3234777/178999427-8e08fcd7-2c60-4ac3-a1a8-ef158577ac45.png)
![Screenshot 2022-07-14 at 16 55 31](https://user-images.githubusercontent.com/3234777/178999446-9e758675-f73e-4da9-91e3-28999c68ee58.png)

**Comment by pavelsokolov** [comment]
This was implemented.
