### ISSUE TITLE
Presentation card redesign

### ISSUE THREAD

**Issue by booski** [dsv-su/play#104]
There has been a number of complaints that the current "card" view is cluttered and difficult to read.

We could add a second display option that uses a wider format along these lines (horrible ascii-art to emphasize it's just a concept):
```
+------------------------------------------------------------------------------+
|+-------------+   Title                                                  |   ||
||             |                                                          | S ||
||    thumb    |   Description,                                           | T ||
||             |   possibly multiple lines                                | U ||
||             |                                                          | F ||
|+-------------+   Tags, etc                                              | F ||
+------------------------------------------------------------------------------+
```

The STUFF part on the right would contain the buttons for editing, sharing etc that are currently only visible on hover.

**Comment by booski** [comment]
When implementing this, the old layout should be retained as an option.

The user should have the ability to switch layouts as needed, and the choice should be remembered between sessions.

**Comment by pavelsokolov** [comment]
Two new layouts were added; table and list. Implemented on all reasonable views (except Manage presentations, need to merge the blade templates first)

**Comment by pavelsokolov** [comment]
A user shouldn't jump to the top of the page when switching the layout (currently a simple redirect->back is used)

**Comment by pavelsokolov** [comment]
This was implemented.
