### ISSUE TITLE
Manage Presentations: Too many presentation cards under each course

### ISSUE THREAD

**Issue by Andrenux** [dsv-su/play#105]
Problem: After expanding a course under "My Courses" under "Manage Presentations", a long list of presentation cards is shown, making difficult to overview the list.
Solution: show only 7 (recent) presentations with possibility to expand to the whole list by clicking on "+" (see attached Mockup)

![expand+](https://user-images.githubusercontent.com/103028966/161712237-6f02513b-ca04-4e7e-b539-51841c098107.png)

**Comment by pavelsokolov** [comment]
This should be solved once #100 is implemented
