### ISSUE TITLE
Manage Presentations: categorize presentations under each course, based on themes/tags

### ISSUE THREAD

**Issue by Andrenux** [dsv-su/play#106]
Feature Request: in the process of managing presentations, teachers need to be able to categorize presentations in course modules/themes, mirroring the course themes in ilearn (see attached mockups). Course themes are used especially for distance-based courses. This categorization should also be visible in “Navigate” <course_name>.
Solution: teachers should be able to tag presentations with keywords including the name of the theme/module, so that headings are created for the presentations in the course.

![IlearnObidam](https://user-images.githubusercontent.com/103028966/161719652-dc6923df-b90b-4d1e-90cc-d7079da2c40a.png)
![Play_Presentations_sorted_under_headings_themes](https://user-images.githubusercontent.com/103028966/161719671-ff19d97e-dc2e-4750-b905-b0ff497baf19.png)

**Comment by pavelsokolov** [comment]
It was suggested that a course admin could choose certaing tags that would act as couse subheadings (like top level tags). Then, presentations could be assigned to those tags and would be displayed organized in subheadings under the course heading.

ALDA VT2022

tag 'WP01'
presentations
tag 'WP02'
presentations
...

**Comment by pavelsokolov** [comment]
Added Course Tags:

<img width="788" alt="Screenshot 2022-05-11 at 17 12 57" src="https://user-images.githubusercontent.com/3234777/167885087-3e7c9e88-8a3c-4451-a9d7-31df4edbc648.png">
<img width="669" alt="Screenshot 2022-05-11 at 17 12 28" src="https://user-images.githubusercontent.com/3234777/167885094-777bb5ee-5b28-4beb-83ab-cd4693673009.png">
