### ISSUE TITLE
Upload: file format should be checked before the actual uploading

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#109]
Now one needs to wait until the file upload is done, before the error is thrown. This needs to be changed to the filetype is checked before uploading.

**Comment by orkit** [comment]
And this is happening right now. Before the files are sent to the play-store, the mime type is validated. If you have discovered something wrong, it would be good if you could explain a little more what the problem is.

**Comment by pavelsokolov** [comment]
I tend to consider this as done, since we have now restricted the upload input field to only video-extensions, and introducing some more advanced mimetype checks is giving more problems that it solves. So i think it's alright if a user gets an error upon uploading some spoofed video file.
