### ISSUE TITLE
Implement "my videos" view

### ISSUE THREAD

**Issue by booski** [dsv-su/play#11]
The view should list all videos a person has any management rights on (currently being a presenter, in future also course admin).

Listed videos should by default be grouped by course and sorted by date. The view should be filterable on at least freetext, course, date, daterange, location and upload type. Tags probably cover most of those categories.

**Comment by pavelsokolov** [comment]
Filters are currently in place:
 - free text: matches video title
 - tags: matches videos with all chosen tags (can be revised the way around, so it displays all videos that have any chosen tag)
 - course: matches all videos belonging to selected courses
 - date range picker with presets, matches 'creation' or 'recorded' attributes
 
We don't really have Lecture halls assignments, but they could be handled as tags, as well as upload types can, so i consider this as done for now.
