### ISSUE TITLE
View presentations titles in English

### ISSUE THREAD

**Issue by Andrenux** [dsv-su/play#112]
Presentation titles should be shown in English, if the user has selected English in the language drop-down menu. Similarly with the title displayed on the presentation poster. Right now the system shows only the Swedish title by default (e.g. see "Föreläsning 5" for DSHI), regardless of the selected language.

**Comment by pavelsokolov** [comment]
Presentation cards have now their titles translated, and it defaults to swedish if there's no english translation.
