### ISSUE TITLE
Poster and thumbnail creation

### ISSUE THREAD

**Issue by booski** [dsv-su/play#12]
The backend should be able to create thumbnails and poster images when they don't already exist. Probably using ffmpeg.

**Comment by orkit** [comment]
Manual upload
Thumbnail and poster generation have been added for manual upload. Manual upload of a presentation takes place in two steps. 
1. The presentation metadata is entered into a form along with the video files. 
2. A thumbnails for the landing page is generated and posters for each video are generated. The uploader can regererate both the thumb and the poster.

**Comment by orkit** [comment]
Manual Download
Thumbnail and poster generation have been added for download. A presentation can be downloaded, the video files and the metadata can be modified before uploading it again.
