### ISSUE TITLE
Presentation deletion

### ISSUE THREAD

**Issue by booski** [dsv-su/play#13]
It should be possible to delete presentations, but the details regarding who should be allowed to do that are unclear:

 - since more than one person can 'own' a presentation, should either be allowed to delete it?
 - maybe admin-only feature?

**Comment by orkit** [comment]
- Deletion of a presentation from the platform is implemented.
- A delete notification to play store is implemented.

Once the above issues have been investigated/clarified, the delete function is ready to be fully implemented.

**Comment by orkit** [comment]
Activate the delete button.
Make sure all related models are deleted.
Make sure a 'delete' - notifications is sent to play-store and make the button visible to users with delete permissions (Admins, CourseAdmins, Individual etc).
Perhaps there should be a log of deleted presentations for Admins ?
