### ISSUE TITLE
Manual upload validation

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#14]
Add validation to the Manual upload view:
- Presenters - presenters username should match existing username in Daisy?
- Courses - course designation should match existing courses.

**Comment by booski** [comment]
Yes, presenter username should be a valid SU username. There may be situations where an external presenter is invited though, so allowing "pure" names with no connection to an SU user may be desirable as a future feature.

**Comment by orkit** [comment]
Presenters - The name of the presenter is looked up against sukat and the username is stored in the upload.

Course - The course name is looked up against stored courses (from Daisy) and the course designation is stored in the upload.
