### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#22]
Permissions. 

Sign In:
Entitlement student or staff to log in. 

Handle menu
To see how to handle the menu, you must own a presentation. All users are allowed to own a presentation.

Upload
To be able to see the upload menu, you must have a upload entitlement. Erik will set a upload entitlement for everyone who needs it.

Admin
Administrators and the admin menu can only be viewed and accesed by those with a special admin-entitlement.

**Comment by booski** [comment]
The entitlement for upload is dsv-user:play-uploader.

The entitlement for admin is dsv-user:play-admin.
