### ISSUE TITLE
Tweaking the footer

### ISSUE THREAD

**Issue by booski** [dsv-su/play#25]
Two things that I'd like to change in the footer:
 - The address text in the left column is gray instead of white
 - The links in the footer should be these:
   - Ilearn (https://ilearn2.dsv.su.se)
   - Play (https://play.dsv.su.se)
   - Daisy (https://daisy.dsv.su.se)
   - SciPro (https://scipro.dsv.su.se)

I realize that the play link is somewhat redundant, but this theme will be getting rolled out to the rest of our apps at some point so we might as well have a generic set that is always the same.

Feel free to add further links if I've missed any core student-facing services.

**Comment by orkit** [comment]
Fixed! The links are structured in a two-column layout - it is also possible to use a one-column layout.
