### ISSUE TITLE
Recorder status

### ISSUE THREAD

**Issue by booski** [dsv-su/play#26]
Recorder status should be visible on the /admin/logs page along with the other external statuses.

A recorder can be designated with a similar button to the existing status buttons, with the difference that it should be clickable and lead to the recorder interface. If the recorder API has some suitable function for status indication, it should be used, otherwise any check that indicates the recorder being 'alive' or not is fine.

Configuration of recorders in the ini file could work along these lines:

[recorders]
FriendlyName = recorder.dns.name
OtherRecorder = other.name
...

**Comment by orkit** [comment]
Fixed!
