### ISSUE TITLE
Player needs conditional shibboleth

### ISSUE THREAD

**Issue by booski** [dsv-su/play#27]
Currently, the /multiplayer route is completely unmanaged, that is it is always accessible regardless of a shib session being present or not. This can cause issues if a user that is not currently logged in tries to view a presentation via direct link - the background call for the presentation package will fail due to missing entitlements and the presentation won't load.

The route needs to start checking for a shib session, and do the normal redirect behaviour if no session is found.

Since there may be a need to enable a given presentation to be fully public (no session required) in future, it's important that the option is kept open to allow session-less users to view the route if the requested presentation is fully public.

**Comment by orkit** [comment]
To make a presentation fully public (access without shibboleth authentication) the permission of the presentation must be set to public external. This will exclude the presentation from the shibboleth authentication.
All other permissions require a valid session.
