### ISSUE TITLE
Personalised start page and menus

### ISSUE THREAD

**Issue by booski** [dsv-su/play#34]
The start page and menus should only show videos/courses/semesters that are relevant for the given user.

For students a "relevant course" is a course that the student has a participation on and that isn't considered completed by daisy (/person/{id}/courseSegmentInstances looks promising). 

In the case of staff, "relevant courses" would be courses they are currently working on. The API may currently be missing the ability to find that information in a reasonable way.

Places where this would have an effect:
 - The start page should still be showing the latest recordings, but only for relevant courses
 - The main menu semester lsit should only list relevant semesters
 - The main menu course list should only list relevant courses

If there are no relevant courses, so some list/page becomes empty, the list/page should indicate this with an informational message that explains that there is no content to show due to the user not participating on any course etc.

**Comment by orkit** [comment]
The startpage now displays a personalized selection of menus and videos during 2019-2021 based on the users enrollment. For employees, a new endpoint in daisy has been created to show ongoing participation in courses for employees.
