### ISSUE TITLE
The search function

### ISSUE THREAD

**Issue by booski** [dsv-su/play#37]
The search function has a few bugs/deficiencies:

 - Typing a query and pressing enter (instead of choosing a suggestion) causes an exception.

I guess it just isn't implemented yet, but the search function obviously needs to be able to accept arbitrary search terms and produce a list of results.

A search result page should have filters available to apply to the results, such as semester, course or presenter.

 - When having chosen a suggestion, the resulting query isn't shown in the search bar on the results page, making it more difficult to see where I ended up.

This is mostly an issue when there are no results to show. If there are results, the page shows a heading "senast tillagt från kursen <kurs>" or similar. This heading should also be there when there are no results, and the "no results" message should move from the heading into the area where the results would otherwise show up. In that case, keeping the query around is less critical.
However, once it's possible to type a random query, that query should certainly be displayed in the search bar on the results page.

**Comment by pavelsokolov** [comment]
Closing this issue, since filtering is covered in #38
