### ISSUE TITLE
Filtering on pages

### ISSUE THREAD

**Issue by booski** [dsv-su/play#38]
There should be filtering available on most pages where videos are listed.

 - The search results page should provide a filter function that allows filtering by at least course (text box with suggested completions similar to search), presenter (similar to course) and semester (checkbox-list).

 - A course page should allow filtering by presenter (checkbox-list based on presenters on the course) and semester (default to showing the latest)
 - A presenter page should be filterable by course and semester, using the same approach as on course pages.
 
There are probably further places that would benefit from filtering, the exact filters to offer (at least initially) should be fairly obvious in each case.

**Comment by pavelsokolov** [comment]
This was implemented.
