### ISSUE TITLE
Guided Tour manual

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#39]
Gunnar and Andrea have expressed a wish to have an online guiding manual for users prior to the launch of the platform. The following suggestions have been made to us:

https://github.com/zusamarehan/laravel-tourify
https://shepherdjs.dev/
https://bootstraptour.com/

I have looked through them a bit quickly and they are all a bit outdated but the one I think would be best suited is the bootstrap version.

**Comment by booski** [comment]
I'm higlhy sceptical of having a tour. My reaction to that type of thing is always that it just stops me from doing what I want to do, and it would raise a number of issues regarding knowing when to show the tour to a user.

Instructions on how to do things are of course important, but I'd say stick to tooltips and documentation, not in-app tours.

**Comment by orkit** [comment]
Yes, alright. I have also discussed this with G&A and we came to the conclusion that it is not a good solution. I will close this issue.
