### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by booski** [dsv-su/play#46]
The current i18n state is patchy at best. All hardcoded text in the platform should be internationalized in a consistent way with support for english and swedish.

**Comment by orkit** [comment]
Short description of how the localisation is meant to work:

### Short keys
(Menus, buttons etc)
In the `resources\lang` directory there are subdirectories for every language supported (for now eng and swe). The default application language is English. This is visible in the `app.php` file, which can be found in the \config directory.
Therefore, if you want to use multiple languages, you will have to add them to the resources.
Each language has a folder and a lang.php file. These are the short keys. Note that you must have the same keys in all the translation files of the languages you use. You only have to change the values to respectively match the languages you chose to translate. 

### Translation Strings 
(Entire pages, text, etc)
For views a JSON translation file should be used. In the file the default translation (eng) is the key. For each language a JSON file should be created. For now only swedish is supported (with the file swe.json). Note that if the particular translation string is not found, the __ function will show the translation string key you added in the content.

**Comment by orkit** [comment]
Everything should be reviewed and fixed now.
