### ISSUE TITLE
Bulk video editing

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#49]
It would be nice to be able to edit videos in bulk, i.e. assign a new course manager, give permissions, etc. (in Mediasite we could use folder concept, now we would have to edit each video)

**Comment by orkit** [comment]
Fixed!

**Comment by pavelsokolov** [comment]
First version is there: a6756503196861d529d66cfa91eb31d91adddc91

<img width="906" alt="Screenshot 2022-07-20 at 18 31 24" src="https://user-images.githubusercontent.com/3234777/180023077-142f9f48-6e9e-42d5-9b3c-b1d97819c090.png">
<img width="949" alt="Screenshot 2022-07-20 at 18 32 04" src="https://user-images.githubusercontent.com/3234777/180023084-4dd273a1-8c5d-44d1-9661-00b80df75c2d.png">

**Comment by pavelsokolov** [comment]
This was implemented.
