### ISSUE TITLE
Tweaks to the video cards

### ISSUE THREAD

**Issue by booski** [dsv-su/play#5]
- The "play" icon in the middle of the video can be removed - everything is a video so indicating that it's playable is redundant.
 - Tags:
   * If tags stay non-clickable, they can be removed from being shown entirely. They are still useful for filtering and categorization so they should still be stored.
   * If tags become clickable, remove the quotation marks on each tag. They are already clearly delineated by having a little box, so the marks are redundant.

**Comment by pavelsokolov** [comment]
Playback icon is removed; tags are cleaned from double qoutes on import & clickable & searchable.
