### ISSUE TITLE
Clean up unused views

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#55]
Some of the views are no longer used (partials, manage, etc). This should be cleaned up as well as the generic header for all views (e.g. upload/index uses a different suplay_upload layout).

**Comment by orkit** [comment]
Old views, scss, css and dependecies have been removed. Css and JS dependecies are now pulled in by npm packages, which makes it easier to maintain and update. Css and JS have been minified and are now compiled to a single file.
