### ISSUE TITLE
Checklist before launch

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#56]
Before launch, the following should be reviewed:

<del>**System settings (play.ini)**</del>
<del>-Set app to production</del>
-Set debug to false
<del>-Set app url for production server</del>

**Tokens**
<del>-check with Erik if token secrets needs to change</del>
-Config play-store-prod with new token

**API**
-check with Erik if dedicated SUKAT account is necessary
-Switch to DAISY production API.

**Testmaterial**
<del>-Remove test videos etc</del>

**Comment by booski** [comment]
Production has happened.
