### ISSUE TITLE
Course-level settings

### ISSUE THREAD

**Issue by booski** [dsv-su/play#57]
There are some settings that would benefit from being configurable at the course level instead of (or in addition to) individual presentations:
 - granting additional editing permissions
 - course-level visibility
 - course-level viewing permissions

These settings must both be able to be fallbacks (for when no setting exists on the presentation) and overrides (ignoring whatever is set on the presentation). How to implement this is unclear, so initially we only implement editing permissions since they must be purely additive.

There should be two routes to the permissions editing view:
 - **Manage > Manage recording > Edit course**: The presentation list should be reworked to group by course, and each course heading should have an edit button if the viewing user is a course admin.
 - **Manage > Manage courses > Edit course**: Manage courses is a new view that simply lists all courses a user has manage access to. If the user has no manage access, hide the menu item as well.

**Comment by orkit** [comment]
Course level configuration. A course administrator can now grant the (as above described) permissions, and the settings will be fallbacks or override existing presentation settings. The default course level setting is: 
-	Group permission DSV Students and Staff, all the presentations with this permission can be viewed by DSV students and Staff (after a successful SU login).
-	Visibility 
-	Not Downloadable
-	No individual permission settings (except for play-administrator)

Exceptions apply to the following states:
1.)	When a course level setting is in default, a presentation setting is set with custom group permission, which will override the course level setting.
2.)	When a course level setting, ‘group permission,’ is set to Public, a presentations permission setting overrides the course level setting.

**Comment by pavelsokolov** [comment]
Admins should be able to edit all courses, also there should be a link to Manage Courses for admins

**Comment by orkit** [comment]
Alright, I will add that.

**Comment by orkit** [comment]
Fixed.

**Comment by pavelsokolov** [comment]
There still no 'manage courses' menu link for admin role.
Permission setup shall be revised, for example right now course/id/edit route is locked to Courseadmin or Administrator play role, while it can even be a student or someone else who has an edit/delete access for a given course.

**Comment by orkit** [comment]
The menu link is now added but it would be good to add some filtering or a search function for Admins, I will create a seperate issue for this.

Regarding permissions setup. If I understand you correctly, you would like a single user who has been authorized to edit/delete course presentations to also have permission to edit course settings?

**Comment by pavelsokolov** [comment]
Looks like there's another issue. If you set Course to be donwloadable, it doesn't affect associated presentations, because 'download' attribute can't be NULL for videos, therefore they're not downloaded by default and have to be set so. Thus, course level permission doesn't matter here unless you configure each individual presentation.

**Comment by pavelsokolov** [comment]
@orkit 
> Regarding permissions setup. If I understand you correctly, you would like a single user who has been authorized to edit/delete course presentations to also have permission to edit course settings?

No. I mean only course permissions. If a single user who is not a course admin was granted 'edit' permission, he/she can't access course admin view, but he/she shall be able to no matter which role he has.

**Comment by orkit** [comment]
> Looks like there's another issue. If you set Course to be donwloadable, it doesn't affect associated presentations, because 'download' attribute can't be NULL for videos, therefore they're not downloaded by default and have to be set so. Thus, course level permission doesn't matter here unless you configure each individual presentation.

No, I'm not experiencing anything wrong here. If a course setting is set to downloadable, an attribute will be added to 'download_setting' which ensures that all associated presentations are downloadable, see check_download () in the Visibility class.

**Comment by orkit** [comment]
> @orkit
> 
> > Regarding permissions setup. If I understand you correctly, you would like a single user who has been authorized to edit/delete course presentations to also have permission to edit course settings?
> 
> No. I mean only course permissions. If a single user who is not a course admin was granted 'edit' permission, he/she can't access course admin view, but he/she shall be able to no matter which role he has.

If a person gets the permission 'edit' or 'delete' for a course then that person can edit the specific course this is handled by middleware and the shibboleth variable (and not 'play_role'). However, the person can not edit course settings, it is for the time being only for course managers.

I think everything is fixed now and will close this issue. Feel free to reopen if something is not right.

**Comment by pavelsokolov** [comment]
Ok, i think for consistency sake a person with 'edit' permission for a course should be able to edit that course settings. However i don't think that will ever be the case, so we can leave it as a future enhancement.

**Comment by orkit** [comment]
This is now fixed!
