### ISSUE TITLE
Shortening the playback URL

### ISSUE THREAD

**Issue by booski** [dsv-su/play#6]
This is an example of a URL in its current format:
https://play-dev.dsv.su.se/multiplayer/?presentation=https://play-dev.dsv.su.se/presentation/15

Having an entire fully qualified URL in the presentation argument looks slightly confusing and makes the URL unnessecarily long. It can be shortened to this with no other changes (works right now):
https://play-dev.dsv.su.se/multiplayer/?presentation=/presentation/15

**Comment by booski** [comment]
Further shortening. The URL format for presentation playback should be this:

<server>/multiplayer/?p=<presentation-id>&l=<list-id>

**Comment by orkit** [comment]
Fixed!
