### ISSUE TITLE
Course association for manual uploads should indicate the course instances rather than designation

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#68]
It's very common that a teacher uploads a recorded video for the upcoming/past course. Therefore the 'recorded' date field and designation might produce inconsistent data. We need another way to determine the course instance (i.e. Designation + term + year), the suggested option is to switch to using courseSegmentInstances (= courses) rather than designations.

Use case: a video is recorded and uploaded in HT, while the course is about to be given in VT.

**Comment by orkit** [comment]
The uploader can now specify which course with designation, term and year the video should be associated with.
