### ISSUE TITLE
Fix backend authentication

### ISSUE THREAD

**Issue by booski** [dsv-su/play#7]
Due to the way shibboleth works, it is currently necessary to manually visit play-store/login to get a session before any videos will play. This obviously won't work in production.

One of these will be necessary:
 - The authentication gets reworked so that the platform sends a token to the backend on each player load, no shib on play-store
 - Initiate a shib session on play-store in the background somehow on player load

**Comment by orkit** [comment]
The authentication has been reworked. The platform sends and ticket(token) on each player load. The token sent is subject to the rights of the video. The token can be used to check permissions at the permission endpoint api.

**Comment by booski** [comment]
This is now fully working as intended.
