### ISSUE TITLE
New video playback speed settings

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#79]
New speed values to append: 0.8 (requested my Martin Henkel), 1.25, 1.75 (gradation by 0.25 is widely used, see Youtube)

**Comment by booski** [comment]
New values are added and committed to the player repo:
0.75, 1, 1.25, 1.5, 1.75, 2

I stuck to a consistent increment instead of having 0.8 as an outlier.

**Comment by orkit** [comment]
The player has been updated. I am working on a script to automate the update in the platform.
