### ISSUE TITLE
Comments from Martin Henkel

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#80]
<del>* Rename "Manage recordings" to "Manage presentations" (check other occurencies as well)</del>
* All redirects should have messages explaining what has happened.

### DOWNLOAD PRESENTATION

<del>* There should be a placeholder for the presentation while it is being uploaded.
<del>* The right panel looks a bit unfinished. The "Choose files" button is clipped at the bottom (Chrome).
<del>* Reduce the size of the infobox with "Up to 4 media files per presentation can be uploaded ....": remove "When uploading, a default thumbnail is generated." 

<del>* Rework Upload files subview, integrate it into main presentation data, possibly like the Edit presentation view. 

 <del>* New streams could be added by 'Add' button, like presenters, users, and removed by 'Trash' button. </del>
<del>* "Files to upload" only displays one file, should be fixed/reworked

### MANAGE PRESENTATIONS
<del>- Make the language consistent. For the small globe icon in the corner of a video, it says "External access enabled". It should be "External playback enabled", just like in the course settings. On Manage presentation's small icons there is a third variant: "Viewing permissions".</del>
<del>- There are some terms that need to be used consistently: "External" or "Audience", "Access" or "Playback". </del>

### MANAGE COURSES
<del> - Slightly large icons / surfaces. Only two courses are visible on a Full HD screen. Probably collapse the courses? </del>
<del> - Viewing permission box should be renamed to be consistent with other boxes, i.e. named 'Playback' instead of the value. </del>
<del>- Rename the Edit button to Settings?</del>

### COURSE SETTINGS
<del>- Rename Update to Save & Close or something like that. Add a success message when redirecting to the main page (applies to all redirects in the app).</del>
- Separate boxes with permissions (it doesn't make sense to merge them on this view)
<del>- Separate permissions counter from the Add button (applies to all views)</del>
<del>- Would be great to be able to limit playback to only those who take the course.</del> It's done via entitlements.
- Toggles that are in the "off" position look disabled (ie grey). We need to make it more obvious that it can be switched. 
<del>- Playback group permissions options are not translated - displayed in Swedish all the time.</del>
<del>- Lacks Swedish translation of "No individual user permissions added" when the list is empty.</del>

**Comment by orkit** [comment]
These things are fixed:
(Download presentation)
-Rename "Manage recordings" to "Manage presentations" (check other occurencies as well).

(Manage presentations)
-Make the language consistent. For the small globe icon in the corner of a video, it says "External access enabled". It should be "External playback enabled", just like in the course settings. 

(Manage courses)
-Rename the Edit button to Settings?

(Course settings)
-Rename Update to Save & Close or something like that. Add a success message when redirecting to the main page (applies to all redirects in the app).

(This is already in place)
-Would be great to be able to limit playback to only those who take the course.

(Im working with this)
The right panel looks a bit unfinished. The "Choose files" button is clipped at the bottom (Chrome).
Reduce the size of the infobox with "Up to 4 media files per presentation can be uploaded ....": remove "When uploading, a default thumbnail is generated."
Rework Upload files subview, integrate it into main presentation data, possibly like the Edit presentation view.

    New streams could be added by 'Add' button, like presenters, users, and removed by 'Trash' button.
    "Files to upload" only displays one file, should be fixed/reworked
