### ISSUE TITLE
Manage presentations view

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#84]
It would be good to add designation to the front of the list shown in the 'Manage Presentations' view similar to the list in 'Manage Courses'.
![Screenshot 2022-01-27 at 11 34 54](https://user-images.githubusercontent.com/22212903/151342840-89d42236-5e07-4958-8a09-92490c2ac370.png)
![Screenshot 2022-01-27 at 11 40 13](https://user-images.githubusercontent.com/22212903/151342899-5ba75df6-7eb9-4283-9cd0-58d7d178bb5e.png)

**Comment by pavelsokolov** [comment]
fixed in 1bb9bda8d364580cf5d9fee8679293034af8ac00
