### ISSUE TITLE
Mediasite import should respect offline and private statuses

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#85]
When importing presentations from media sites, I discovered that a presentation that has been marked as hidden in media sites appears in the import list in the mediasite import tool. Should hidden media site presentations be imported? If not, it should be avoided or there should be a way to opt it out manually.
![Screenshot 2022-01-27 at 11 22 04](https://user-images.githubusercontent.com/22212903/151359633-6db34235-089f-4ea8-8780-2216b559b203.png)
![Screenshot 2022-01-27 at 11 22 19](https://user-images.githubusercontent.com/22212903/151361529-506cefcf-3510-49e5-ac21-0366b85cb279.png)

It would also be good if individual presentations in the list could be deselected.

**Comment by pavelsokolov** [comment]
We don't respect any privacy and permission settings created on mediasite, so we import all presentations.

We can of course enhance the mediasite import interface, but I am not sure if it's reasonable. The idea was to import presentations in batches, and then disconnect mediasite recorders, so this import won't be used regularly. So I'd suggest leaving it until we're done with other issues.

**Comment by orkit** [comment]
I mean that if we import a batch of older presentations and the teacher has explicitly set in mediasite that that presentation should not be viewable, it still will be imported (It could be easy to make a mistake here). I do not mean to change the media site interface in any way, but wonder if there is some kind of flag that can be used so that the presentation does not appear in the list of possible presentations to import.

**Comment by booski** [comment]
Aren't mediasite imports going to be done on request from the responsible teacher anyway? In that case I suggest one of these options:
 - we add the option to deselect presentations to import, and ask the requesting teacher to check whether there are presentations they don't want
 - we notify teachers after importing that they should look through the imported material and see if they want to hide something

**Comment by pavelsokolov** [comment]
It's not a problem to get the presentation status (offline, private) and append 'visiblity: 0' to the passed json. In that case we migrate everything and save the visibility setting. But that requires play-store not stripping that attribute away.
<img width="183" alt="Screenshot 2022-02-03 at 18 16 35" src="https://user-images.githubusercontent.com/3234777/152371331-360362ee-0d8e-475e-9185-7fdb89a3dd9c.png">

**Comment by booski** [comment]
The daemon on play-store has been updated.

If a mediasite import job includes a "status" field next to the "id", "title", etc fields, it will now be passed on. If the field doesn't exist it will be populated with an empty string. This should probably change to some sane default or simply always expect the field to be present.

**Comment by pavelsokolov** [comment]
'visibility' attribute is now passed to play-store for mediasite presentations (f73d3ade14cca665f48eef4b3a913b255198d297), it's set to 0 when the presentation is either 'offline' or 'private'.

**Comment by pavelsokolov** [comment]
Fixed in f73d3ade14cca665f48eef4b3a913b255198d297
