### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by pavelsokolov** [dsv-su/play#90]
It should be possible to upload subtitles to a presentation. Also, some automatic subtitling tool would be nice to have.

**Comment by booski** [comment]
subtitles are on the todo-list for the player, but probably won't be done in time for launch

**Comment by booski** [comment]
Subtitle support is now in the player. 

Subtitles will be picked up from the top-level "subtitles" field in the package json. It should point to a file in VTT format (https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API).

The button to toggle subtitles will only be displayed on presentations that have subtitles at all.

Currently only one subtitle track is supported.
