### ISSUE TITLE
Refactor Middleware authorization and tickethandler

### ISSUE THREAD

**Issue by orkit** [dsv-su/play#93]
As a presentation can belong to several courses, there will be some conflicts in the system that must be resolved. Since the course setting takes over the presentation setting, a problem arises if the course administrators set the courses differently - which setting should apply? This affects token management for playback and middleware for user authorization.

**Comment by pavelsokolov** [comment]
I would say that if a course is set to hidden/not downloadable, then this setting should be propagated to all its presentation no matter what other courses they have.

**Comment by orkit** [comment]
Yes, thats how its set now but I'm thinking of the playback permissions. If there are different playback permissions in the different courses. If, for example, one course is set to 'Public' and another to 'Staff' etc.
I think for now I will set it so that if a presentation belongs to several courses and there are different settings in each course then it should be set to the default setting, 'Students and staff' and then we can discuss this further.

**Comment by orkit** [comment]
TicketHandler has now been refactored to make it easier to change future logic. For now the course settings take over any individual settings. If a presentation belongs to multiple courses and there are multiple course settings, the presentation setting returns to the default course setting.
