### ISSUE TITLE
All views should be linkable

### ISSUE THREAD

**Issue by booski** [dsv-su/play#95]
Some views can't be linked to currently, which is bad. One example of this is the "All presentations" tab on the start page.

This should be fixed so that any page that can be viewed can also be reached by copying the URL from the URL bar when viewing it.

**Comment by booski** [comment]
A similar issue exists when filtering a search - there is no way to link to the filtered results.

**Comment by pavelsokolov** [comment]
/presenter, /semester, /tag, /designation views filters are now passed to URL

e.g.

https://play-app-dev.dsv.su.se/designation/DB?&presenter=bergh,athel&tag=Lilla%20H%C3%B6rsalen

**Comment by pavelsokolov** [comment]
Now search results are also linkable.
