### ISSUE TITLE
Making suggested users easier to distinguish

### ISSUE THREAD

**Issue by booski** [dsv-su/play#98]
When searching for users, for example when editing a presentation, it can be hard to know which user to pick from the list if they only differ by username:
![Screenshot_2022-03-24_11-26-58-mod-2](https://user-images.githubusercontent.com/1434152/159898485-ceb94dbb-915b-4ed5-9e09-4e51c2d3b31f.png)

Adding a tag/emblem on users with a DSV entitlement would make this easier:
![Screenshot_2022-03-24_11-26-58-mod](https://user-images.githubusercontent.com/1434152/159898593-8becf90e-748b-4afd-b744-ccd9037005ca.png)

I'd suggest having a blue tag for staff and a green tag for students, matching the access cards. The text could be just DSV to save space, or DSV staff/DSV student as appropriate if it can fit.

Further possible improvements that could be made:
 - List more than 4 suggestions, preferrably maxing out at 10-20 and scrolling the list
 - Sort users with DSV entitlements to the top of the list so they turn up sooner, preferrably staff first, students second and others after that

**Comment by pavelsokolov** [comment]
Labels were added and user search now works just like courses/tags.

**Comment by pavelsokolov** [comment]
Reopening this since I have now realized 'individual permissions' should also support these labels.
